# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

def shared_pods
 pod 'SDWebImage'
end

target 'CommunicationNotificationSample' do
  shared_pods

end

target 'CommunicationNotificationService' do
  use_frameworks!
  pod 'SDWebImage'
  end
